-- ─── Enums ───────────────────────────────────────────────────────────────────

CREATE TYPE "node_type" AS ENUM (
    'challengeNode',
    'activityNode',
    'gatewayNode',
    'startNode',
    'endNode',
    'infoNode',
    'gamificationEventNode',
    'andSplitNode',
    'andJoinNode'
);

CREATE TYPE "flow_element_instance_status" AS ENUM (
    'Created',
    'Todo',
    'In Progress',
    'Completed',
    'Error'
);

CREATE TYPE "process_instance_status" AS ENUM (
    'Running',
    'Completed',
    'Error'
);

CREATE TYPE "node_definition_visibility" AS ENUM (
    'Public',
    'Team'
);

-- These types are needed by the process engine PostgreSQL functions
CREATE TYPE "execution_mode" AS ENUM ('Manual', 'Automatic');
CREATE TYPE "gamification_type" AS ENUM ('None', 'Points', 'Badges');
CREATE TYPE "page" AS ENUM ('Editor', 'Tasks', 'Monitoring', 'Team', 'Stats', 'Shop');

-- ─── better-auth tables ───────────────────────────────────────────────────────

CREATE TABLE "user" (
    "id"                   TEXT        NOT NULL PRIMARY KEY,
    "name"                 TEXT        NOT NULL,
    "email"                TEXT        NOT NULL UNIQUE,
    "email_verified"       BOOLEAN     NOT NULL DEFAULT FALSE,
    "image"                TEXT,
    "username"             TEXT        UNIQUE,
    "avatar"               TEXT,
    "is_dark_mode_enabled" BOOLEAN     NOT NULL DEFAULT FALSE,
    "language"             TEXT        NOT NULL DEFAULT 'de',
    "created_at"           TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at"           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "session" (
    "id"         TEXT        NOT NULL PRIMARY KEY,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "token"      TEXT        NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "ip_address" TEXT,
    "user_agent" TEXT,
    "user_id"    TEXT        NOT NULL REFERENCES "user"(id) ON DELETE CASCADE
);

CREATE TABLE "account" (
    "id"                       TEXT        NOT NULL PRIMARY KEY,
    "account_id"               TEXT        NOT NULL,
    "provider_id"              TEXT        NOT NULL,
    "user_id"                  TEXT        NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    "access_token"             TEXT,
    "refresh_token"            TEXT,
    "id_token"                 TEXT,
    "access_token_expires_at"  TIMESTAMPTZ,
    "refresh_token_expires_at" TIMESTAMPTZ,
    "scope"                    TEXT,
    "password"                 TEXT,
    "created_at"               TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at"               TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "verification" (
    "id"         TEXT        NOT NULL PRIMARY KEY,
    "identifier" TEXT        NOT NULL,
    "value"      TEXT        NOT NULL,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─── Domain tables ────────────────────────────────────────────────────────────

CREATE TABLE "team" (
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at"   TIMESTAMPTZ NOT NULL DEFAULT now(),
    "name"         VARCHAR     NOT NULL,
    "created_by"   TEXT        NOT NULL REFERENCES "user"(id),
    "color_scheme" JSONB
);

CREATE TABLE "role" (
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "name"       TEXT        NOT NULL,
    "belongs_to" BIGINT      NOT NULL REFERENCES "team"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "color"      TEXT        NOT NULL,
    "pages"      JSONB       NOT NULL DEFAULT '{"allowed_pages":[]}'::JSONB
);

CREATE TABLE "profile_role_team" (
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "profile_id" TEXT        NOT NULL REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "role_id"    BIGINT      NOT NULL REFERENCES "role"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "team_id"    BIGINT      NOT NULL REFERENCES "team"(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE UNIQUE INDEX "unique_profile_role_team" ON "profile_role_team" (profile_id, role_id, team_id);

CREATE TABLE "profile_team" (
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "profile_id" TEXT        NOT NULL REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "team_id"    BIGINT      NOT NULL REFERENCES "team"(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "invitation" (
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "email"      TEXT        NOT NULL,
    "team_id"    BIGINT      NOT NULL REFERENCES "team"(id)
);

CREATE TABLE "process_model" (
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at"  TIMESTAMPTZ NOT NULL DEFAULT now(),
    "name"        VARCHAR     NOT NULL,
    "description" TEXT,
    "created_by"  TEXT        REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE SET NULL,
    "updated_by"  TEXT        REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE SET NULL,
    "updated_at"  TIMESTAMP WITHOUT TIME ZONE,
    "belongs_to"  BIGINT      NOT NULL REFERENCES "team"(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "flow_element" (
    "id"                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at"            TIMESTAMPTZ NOT NULL DEFAULT now(),
    "type"                  node_type   NOT NULL,
    "model_id"              BIGINT      NOT NULL REFERENCES "process_model"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "position_x"            DOUBLE PRECISION NOT NULL,
    "position_y"            DOUBLE PRECISION NOT NULL,
    "width"                 DOUBLE PRECISION,
    "height"                DOUBLE PRECISION,
    "data"                  JSONB,
    "parent_flow_element_id" BIGINT     REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE SET NULL,
    "z_index"               BIGINT,
    "execution_url"         TEXT
);

CREATE TABLE "activity_element" (
    "id"                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at"              TIMESTAMPTZ NOT NULL DEFAULT now(),
    "flow_element_id"         BIGINT      NOT NULL UNIQUE REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "next_flow_element_id"    BIGINT      REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE SET NULL,
    "next_flow_element_handle" TEXT
);

CREATE TABLE "start_element" (
    "id"                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at"              TIMESTAMPTZ NOT NULL DEFAULT now(),
    "flow_element_id"         BIGINT      NOT NULL UNIQUE REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "next_flow_element_id"    BIGINT      REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE SET NULL,
    "next_flow_element_handle" TEXT
);

CREATE TABLE "end_element" (
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    "flow_element_id" BIGINT      NOT NULL UNIQUE REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "gateway_element" (
    "id"                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at"                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    "flow_element_id"              BIGINT      NOT NULL UNIQUE REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "next_flow_element_true_id"    BIGINT      REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE SET NULL,
    "next_flow_element_false_id"   BIGINT      REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE SET NULL,
    "next_flow_element_true_handle" TEXT,
    "next_flow_element_false_handle" TEXT
);

CREATE TABLE "and_split_element" (
    "id"                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at"                TIMESTAMPTZ NOT NULL DEFAULT now(),
    "flow_element_id"           BIGINT      NOT NULL UNIQUE REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "next_flow_element_id_1"    BIGINT      REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE SET NULL,
    "next_flow_element_id_2"    BIGINT      REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE SET NULL,
    "next_flow_element_handle_1" TEXT,
    "next_flow_element_handle_2" TEXT
);

CREATE TABLE "and_join_element" (
    "id"                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at"                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    "flow_element_id"            BIGINT      NOT NULL UNIQUE REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "previous_flow_element_id_1" BIGINT      REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE SET NULL,
    "previous_flow_element_id_2" BIGINT      REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE SET NULL,
    "next_flow_element_id"       BIGINT      REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE SET NULL,
    "next_flow_element_handle"   TEXT
);

CREATE TABLE "node_definition" (
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "definition" JSONB       NOT NULL DEFAULT '{}'::JSONB,
    "created_by" TEXT        REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "team_id"    BIGINT      REFERENCES "team"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "visibility" node_definition_visibility NOT NULL DEFAULT 'Team'::node_definition_visibility
);

CREATE TABLE "teams_node_definitions" (
    "id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at"         TIMESTAMPTZ NOT NULL DEFAULT now(),
    "team_id"            BIGINT      NOT NULL REFERENCES "team"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "node_definition_id" BIGINT      REFERENCES "node_definition"(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE "process_instance" (
    "id"               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    "process_model_id" BIGINT      NOT NULL REFERENCES "process_model"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "status"           process_instance_status NOT NULL DEFAULT 'Running'::process_instance_status,
    "completed_at"     TIMESTAMPTZ
);

CREATE TABLE "flow_element_instance" (
    "id"             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at"     TIMESTAMPTZ NOT NULL DEFAULT now(),
    "instance_of"    BIGINT      NOT NULL REFERENCES "flow_element"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "status"         flow_element_instance_status NOT NULL DEFAULT 'Created'::flow_element_instance_status,
    "is_part_of"     BIGINT      NOT NULL REFERENCES "process_instance"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "completed_at"   TIMESTAMPTZ,
    "completed_by"   TEXT        REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE SET NULL,
    "status_message" TEXT
);

CREATE UNIQUE INDEX "unique_instance_of_is_part_of" ON "flow_element_instance" (instance_of, is_part_of);

CREATE TABLE "data_object_instance" (
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "is_part_of" BIGINT      NOT NULL REFERENCES "process_instance"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "name"       TEXT        NOT NULL,
    "value"      JSONB
);

CREATE UNIQUE INDEX "data_object_instance_unique_constraint" ON "data_object_instance" (is_part_of, name);

CREATE TABLE "statistics" (
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "experience" BIGINT      NOT NULL DEFAULT 0,
    "coins"      BIGINT      NOT NULL DEFAULT 0,
    "profile_id" TEXT        NOT NULL REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "team_id"    BIGINT      NOT NULL REFERENCES "team"(id) ON UPDATE CASCADE ON DELETE CASCADE,
    "badges"     JSONB       NOT NULL DEFAULT '{"badges":[]}'::JSONB
);

CREATE TABLE "config" (
    "key"   TEXT NOT NULL PRIMARY KEY,
    "value" TEXT NOT NULL
);

-- ─── Views ────────────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW "profiles_with_roles" AS
SELECT
    u.id       AS profile_id,
    u.email,
    u.username,
    pt.team_id,
    r.id       AS role_id,
    r.name     AS role_name,
    r.color    AS role_color
FROM profile_team pt
JOIN "user" u ON u.id = pt.profile_id
LEFT JOIN profile_role_team prt ON pt.team_id = prt.team_id AND pt.profile_id = prt.profile_id
LEFT JOIN role r ON prt.role_id = r.id;
