create table "public"."activity_element" (
                                             "id" bigint generated by default as identity not null,
                                             "created_at" timestamp with time zone not null default now(),
                                             "flow_element_id" bigint not null,
                                             "task" text,
                                             "activity_type" character varying,
                                             "choices" text,
                                             "input_regex" text,
                                             "variable_name" text,
                                             "next_flow_element_id" bigint
);


alter table "public"."activity_element" enable row level security;

create table "public"."flow_element" (
                                         "id" bigint generated by default as identity not null,
                                         "created_at" timestamp with time zone not null default now(),
                                         "type" character varying not null,
                                         "model_id" bigint not null,
                                         "position_x" double precision not null,
                                         "position_y" double precision not null,
                                         "width" double precision,
                                         "height" double precision
);


alter table "public"."flow_element" enable row level security;

create table "public"."process_model" (
                                          "id" bigint generated by default as identity not null,
                                          "created_at" timestamp with time zone not null default now(),
                                          "name" character varying not null,
                                          "description" text,
                                          "created_by" uuid not null,
                                          "updated_by" uuid,
                                          "updated_at" timestamp without time zone,
                                          "belongs_to" bigint not null
);


alter table "public"."process_model" enable row level security;

CREATE UNIQUE INDEX activity_element_flow_element_id_key ON public.activity_element USING btree (flow_element_id);

CREATE UNIQUE INDEX activity_element_pkey ON public.activity_element USING btree (id);

CREATE UNIQUE INDEX flow_element_pkey ON public.flow_element USING btree (id);

CREATE UNIQUE INDEX process_model_pkey ON public.process_model USING btree (id);

alter table "public"."activity_element" add constraint "activity_element_pkey" PRIMARY KEY using index "activity_element_pkey";

alter table "public"."flow_element" add constraint "flow_element_pkey" PRIMARY KEY using index "flow_element_pkey";

alter table "public"."process_model" add constraint "process_model_pkey" PRIMARY KEY using index "process_model_pkey";

alter table "public"."activity_element" add constraint "activity_element_flow_element_id_key" UNIQUE using index "activity_element_flow_element_id_key";

alter table "public"."activity_element" add constraint "public_activity_element_flow_element_id_fkey" FOREIGN KEY (flow_element_id) REFERENCES flow_element(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."activity_element" validate constraint "public_activity_element_flow_element_id_fkey";

alter table "public"."activity_element" add constraint "public_activity_element_next_flow_element_id_fkey" FOREIGN KEY (next_flow_element_id) REFERENCES flow_element(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."activity_element" validate constraint "public_activity_element_next_flow_element_id_fkey";

alter table "public"."flow_element" add constraint "public_flow_element_model_id_fkey" FOREIGN KEY (model_id) REFERENCES process_model(id) ON UPDATE CASCADE not valid;

alter table "public"."flow_element" validate constraint "public_flow_element_model_id_fkey";

alter table "public"."process_model" add constraint "public_process_model_belongs_to_fkey" FOREIGN KEY (belongs_to) REFERENCES team(id) ON UPDATE CASCADE not valid;

alter table "public"."process_model" validate constraint "public_process_model_belongs_to_fkey";

alter table "public"."process_model" add constraint "public_process_model_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id) ON UPDATE CASCADE not valid;

alter table "public"."process_model" validate constraint "public_process_model_created_by_fkey";

alter table "public"."process_model" add constraint "public_process_model_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES profiles(id) ON UPDATE CASCADE not valid;

alter table "public"."process_model" validate constraint "public_process_model_updated_by_fkey";

grant delete on table "public"."activity_element" to "anon";

grant insert on table "public"."activity_element" to "anon";

grant references on table "public"."activity_element" to "anon";

grant select on table "public"."activity_element" to "anon";

grant trigger on table "public"."activity_element" to "anon";

grant truncate on table "public"."activity_element" to "anon";

grant update on table "public"."activity_element" to "anon";

grant delete on table "public"."activity_element" to "authenticated";

grant insert on table "public"."activity_element" to "authenticated";

grant references on table "public"."activity_element" to "authenticated";

grant select on table "public"."activity_element" to "authenticated";

grant trigger on table "public"."activity_element" to "authenticated";

grant truncate on table "public"."activity_element" to "authenticated";

grant update on table "public"."activity_element" to "authenticated";

grant delete on table "public"."activity_element" to "service_role";

grant insert on table "public"."activity_element" to "service_role";

grant references on table "public"."activity_element" to "service_role";

grant select on table "public"."activity_element" to "service_role";

grant trigger on table "public"."activity_element" to "service_role";

grant truncate on table "public"."activity_element" to "service_role";

grant update on table "public"."activity_element" to "service_role";

grant delete on table "public"."flow_element" to "anon";

grant insert on table "public"."flow_element" to "anon";

grant references on table "public"."flow_element" to "anon";

grant select on table "public"."flow_element" to "anon";

grant trigger on table "public"."flow_element" to "anon";

grant truncate on table "public"."flow_element" to "anon";

grant update on table "public"."flow_element" to "anon";

grant delete on table "public"."flow_element" to "authenticated";

grant insert on table "public"."flow_element" to "authenticated";

grant references on table "public"."flow_element" to "authenticated";

grant select on table "public"."flow_element" to "authenticated";

grant trigger on table "public"."flow_element" to "authenticated";

grant truncate on table "public"."flow_element" to "authenticated";

grant update on table "public"."flow_element" to "authenticated";

grant delete on table "public"."flow_element" to "service_role";

grant insert on table "public"."flow_element" to "service_role";

grant references on table "public"."flow_element" to "service_role";

grant select on table "public"."flow_element" to "service_role";

grant trigger on table "public"."flow_element" to "service_role";

grant truncate on table "public"."flow_element" to "service_role";

grant update on table "public"."flow_element" to "service_role";

grant delete on table "public"."process_model" to "anon";

grant insert on table "public"."process_model" to "anon";

grant references on table "public"."process_model" to "anon";

grant select on table "public"."process_model" to "anon";

grant trigger on table "public"."process_model" to "anon";

grant truncate on table "public"."process_model" to "anon";

grant update on table "public"."process_model" to "anon";

grant delete on table "public"."process_model" to "authenticated";

grant insert on table "public"."process_model" to "authenticated";

grant references on table "public"."process_model" to "authenticated";

grant select on table "public"."process_model" to "authenticated";

grant trigger on table "public"."process_model" to "authenticated";

grant truncate on table "public"."process_model" to "authenticated";

grant update on table "public"."process_model" to "authenticated";

grant delete on table "public"."process_model" to "service_role";

grant insert on table "public"."process_model" to "service_role";

grant references on table "public"."process_model" to "service_role";

grant select on table "public"."process_model" to "service_role";

grant trigger on table "public"."process_model" to "service_role";

grant truncate on table "public"."process_model" to "service_role";

grant update on table "public"."process_model" to "service_role";

create policy "Enable everything for authenticated users"
    on "public"."activity_element"
    as permissive
    for all
    to authenticated
    using (true);


create policy "Enable edit for authenticated users"
    on "public"."flow_element"
    as permissive
    for all
    to authenticated
    using (true);


create policy "Enable select for authenticated users only"
    on "public"."process_model"
    as permissive
    for select
    to authenticated
    using (true);


create policy "Enable select for authenticated users only"
    on "public"."profile_role_team"
    as permissive
    for select
    to authenticated
    using (true);
