create table "public"."Statistics" (
                                       "id" bigint generated by default as identity not null,
                                       "created_at" timestamp with time zone not null default now(),
                                       "experience" bigint,
                                       "coins" bigint,
                                       "belongs_to" bigint not null
);


alter table "public"."Statistics" enable row level security;

CREATE UNIQUE INDEX "Statistics_pkey" ON public."Statistics" USING btree (id);

alter table "public"."Statistics" add constraint "Statistics_pkey" PRIMARY KEY using index "Statistics_pkey";

alter table "public"."Statistics" add constraint "public_Statistics_belongs_to_fkey" FOREIGN KEY (belongs_to) REFERENCES profile_team(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Statistics" validate constraint "public_Statistics_belongs_to_fkey";

grant delete on table "public"."Statistics" to "anon";

grant insert on table "public"."Statistics" to "anon";

grant references on table "public"."Statistics" to "anon";

grant select on table "public"."Statistics" to "anon";

grant trigger on table "public"."Statistics" to "anon";

grant truncate on table "public"."Statistics" to "anon";

grant update on table "public"."Statistics" to "anon";

grant delete on table "public"."Statistics" to "authenticated";

grant insert on table "public"."Statistics" to "authenticated";

grant references on table "public"."Statistics" to "authenticated";

grant select on table "public"."Statistics" to "authenticated";

grant trigger on table "public"."Statistics" to "authenticated";

grant truncate on table "public"."Statistics" to "authenticated";

grant update on table "public"."Statistics" to "authenticated";

grant delete on table "public"."Statistics" to "service_role";

grant insert on table "public"."Statistics" to "service_role";

grant references on table "public"."Statistics" to "service_role";

grant select on table "public"."Statistics" to "service_role";

grant trigger on table "public"."Statistics" to "service_role";

grant truncate on table "public"."Statistics" to "service_role";

grant update on table "public"."Statistics" to "service_role";
