create table "public"."and_join_element" (
                                             "id" bigint generated by default as identity not null,
                                             "created_at" timestamp with time zone not null default now(),
                                             "flow_element_id" bigint not null,
                                             "previous_flow_element_id_1" bigint,
                                             "previous_flow_element_id_2" bigint,
                                             "next_flow_element_id" bigint,
                                             "next_flow_element_handle" text
);


alter table "public"."and_join_element" enable row level security;

alter table "public"."activity_element" add column "next_flow_element_handle" text;

alter table "public"."and_split_element" add column "next_flow_element_handle_1" text;

alter table "public"."and_split_element" add column "next_flow_element_handle_2" text;

alter table "public"."gateway_element" add column "next_flow_element_false_handle" text;

alter table "public"."gateway_element" add column "next_flow_element_true_handle" text;

alter table "public"."start_element" add column "next_flow_element_handle" text;

CREATE UNIQUE INDEX and_join_element_flow_element_id_key ON public.and_join_element USING btree (flow_element_id);

CREATE UNIQUE INDEX and_join_element_pkey ON public.and_join_element USING btree (id);

alter table "public"."and_join_element" add constraint "and_join_element_pkey" PRIMARY KEY using index "and_join_element_pkey";

alter table "public"."and_join_element" add constraint "and_join_element_flow_element_id_key" UNIQUE using index "and_join_element_flow_element_id_key";

alter table "public"."and_join_element" add constraint "public_and_join_element_flow_element_id_fkey" FOREIGN KEY (flow_element_id) REFERENCES flow_element(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."and_join_element" validate constraint "public_and_join_element_flow_element_id_fkey";

alter table "public"."and_join_element" add constraint "public_and_join_element_next_flow_element_id_fkey" FOREIGN KEY (next_flow_element_id) REFERENCES flow_element(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."and_join_element" validate constraint "public_and_join_element_next_flow_element_id_fkey";

alter table "public"."and_join_element" add constraint "public_and_join_element_previous_flow_element_id_1_fkey" FOREIGN KEY (previous_flow_element_id_1) REFERENCES flow_element(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."and_join_element" validate constraint "public_and_join_element_previous_flow_element_id_1_fkey";

alter table "public"."and_join_element" add constraint "public_and_join_element_previous_flow_element_id_2_fkey" FOREIGN KEY (previous_flow_element_id_2) REFERENCES flow_element(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."and_join_element" validate constraint "public_and_join_element_previous_flow_element_id_2_fkey";

grant delete on table "public"."and_join_element" to "anon";

grant insert on table "public"."and_join_element" to "anon";

grant references on table "public"."and_join_element" to "anon";

grant select on table "public"."and_join_element" to "anon";

grant trigger on table "public"."and_join_element" to "anon";

grant truncate on table "public"."and_join_element" to "anon";

grant update on table "public"."and_join_element" to "anon";

grant delete on table "public"."and_join_element" to "authenticated";

grant insert on table "public"."and_join_element" to "authenticated";

grant references on table "public"."and_join_element" to "authenticated";

grant select on table "public"."and_join_element" to "authenticated";

grant trigger on table "public"."and_join_element" to "authenticated";

grant truncate on table "public"."and_join_element" to "authenticated";

grant update on table "public"."and_join_element" to "authenticated";

grant delete on table "public"."and_join_element" to "service_role";

grant insert on table "public"."and_join_element" to "service_role";

grant references on table "public"."and_join_element" to "service_role";

grant select on table "public"."and_join_element" to "service_role";

grant trigger on table "public"."and_join_element" to "service_role";

grant truncate on table "public"."and_join_element" to "service_role";

grant update on table "public"."and_join_element" to "service_role";

create policy "Enable for authenticated"
    on "public"."and_join_element"
    as permissive
    for all
    to authenticated
    using (true);
