site_name: ProcessFlow Docs
site_url: https://mertend.github.io/process-flow/
site_author: Merten Dieckmann
site_description: ""
repo_url: "https://github.com/MertenD/process-flow"

theme:
  name: material

extra_css:
  - stylesheets/extra.css

nav:
  - Project Overview: index.md
  - Time Tracking: "timetracking.md"
  - Database: "database.md"